# Generated by Django 5.0.2 on 2024-02-23 11:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_friends_useraccount_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers_relation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='following_relation', to=settings.AUTH_USER_MODEL),
        ),
    ]
