# Generated by Django 5.0.2 on 2024-02-23 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_useraccount_followers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='following',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='follows',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_relation', to=settings.AUTH_USER_MODEL),
        ),
    ]
