# Generated by Django 5.0.2 on 2024-02-23 11:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_useraccount_followers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='follows',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
