# Generated by Django 5.0.2 on 2024-02-23 11:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_useraccount_follows_useraccount_follows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='follows',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
