# Generated by Django 5.0.2 on 2024-02-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_useraccount_follows_useraccount_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
