# Generated by Django 5.0.2 on 2024-02-19 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.TextField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_host', to=settings.AUTH_USER_MODEL)),
                ('members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
