# Generated by Django 5.0.2 on 2024-02-19 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.topic'),
        ),
    ]
